"""
Setuptools build file

:author: KKENNEDY
"""

# Version (Semantic Versioning)
VER_MAJOR = 1
VER_MINOR = 0
VER_PATCH = 0

# Is this a release version? If so, additional data is appended to full version
RELEASE = False

# Release type
REL_TYPE = 'dev0'    # Development Release
# REL_TYPE = 'alpha0' # Alpha Release
# REL_TYPE = 'beta0'  # Beta Release
# REL_TYPE = 'rc1'    # Release Candidate

# -----------------------------------------------------------------------
# DO NOT CHANGE ANYTHING BELOW THIS LINE
# -----------------------------------------------------------------------

import sys, os, time

def generate_ver(filename='labtronyx/version.py'):
    # Get Git Revision
    try:
        import subprocess
        GIT_REVISION = subprocess.check_output(['git', 'rev-parse', 'HEAD']).strip()
    except:
        GIT_REVISION = ''

    # Generate version string
    VERSION = '%d.%d.%d' % (VER_MAJOR, VER_MINOR, VER_PATCH)
    BUILD_DATE = time.strftime("%y%m%d")

    if RELEASE:
        # Post-release build
        FULL_VERSION = '%s-%s' % (VERSION, BUILD_DATE)
    else:
        # Pre-release build
        if GIT_REVISION != '':
            FULL_VERSION = '%s.%s+%s' % (VERSION, REL_TYPE, GIT_REVISION[:7])
        else:
            FULL_VERSION = '%s.%s+%s' % (VERSION, REL_TYPE, BUILD_DATE)

    # Generate version file
    ver_py = """# AUTOGENERATED DURING BUILD

ver_sem = '{version}'
ver_full = '{full_version}'
build_date = '{build}'
git_revision = '{git_revision}'
    """
    with open(filename, 'w') as f:
        f.write(ver_py.format(version=VERSION, full_version=FULL_VERSION,
                              build=BUILD_DATE, git_revision=GIT_REVISION))

    return VERSION, FULL_VERSION

def build_package():
    # Generate version file
    version, full_version = generate_ver()

    # Setup Metadata
    setup_meta = dict(
        # Application name:
        name='Labtronyx',

        # Version number
        version=full_version,

        # Application author details:
        author="Kevin Kennedy",
        author_email="protonyx@users.noreply.github.com",

        # License
        license="MIT",

        # Details
        url="https://github.com/protonyx/labtronyx",

        # Description
        description='Labtronyx Instrument Control',

        # Platforms
        platforms=["Windows", "Mac OS-X", "Linux"],

        # Long Description
        long_description=open("README.rst").read(),

        # Classifiers
        classifiers=[
            "Development Status :: 3 - Alpha",
            "Intended Audience :: Developers",
            "Intended Audience :: Science/Research",
            "License :: OSI Approved :: MIT License",
            "Operating System :: Microsoft :: Windows",
            "Operating System :: POSIX :: Linux",
            "Operating System :: MacOS :: MacOS X",
            "Programming Language :: Python",
            "Programming Language :: Python :: 2.7",
            "Topic :: Software Development :: Libraries :: Python Modules",
            "Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator"
        ],

        # Unit tests
        test_suite="tests.test_suite",

        # Packages
        packages=['labtronyx'],

        # Package data - e.g. non-python modules
        # package_data = {},
        # Include additional files into the package
        include_package_data=True,

        # Dependencies
        extras_require={
            'VISA': ['pyvisa>=1.6'],
            'Serial': ['pyserial']
        },

        install_requires=['ptx-rpc', 'enum34', 'numpy'],

        # Can the project run from a zip file?
        zip_safe = False
    )

    # Additional dependencies for CI and test builds
    if os.environ.get('CI') == 'true' or 'test' in sys.argv:
        setup_meta['install_requires'] += ['pyvisa-sim', 'mock']

    try:
        from setuptools import setup
    except ImportError:
        from distutils.core import setup

    # Setuptools
    setup(**setup_meta)

if __name__ == '__main__':
    build_package()